### ISSUE TITLE
Le programme est là ! :) 

### ISSUE THREAD

**Issue by benchti** [sudweb/estcequecestbientot#4]
Tout est dans le titre ;) 

Une image du slip pour vos petits enfants quand même ;) :  
![selection_107](https://cloud.githubusercontent.com/assets/663816/13492038/1454a99e-e136-11e5-9963-6d74b51e15b7.png)

**Comment by DirtyF** [comment]
@benchti zut, problème de chargement des fontes, quel environnement (OS, Navigateur, version) ?

**Comment by benchti** [comment]
c'était firefox linux .

Ok firefox / chrome linux , maintenant ... reste une petite erreur sur http://fonts.googleapis.com/css?family=Squada+One:100 

![selection_109](https://cloud.githubusercontent.com/assets/663816/13494648/ea695142-e145-11e5-8200-892d739d02d4.png)

**Comment by thom4parisot** [comment]
@benchti certains reportent ces problèmes pque AdBlocker. Tu en utilises un ?

**Comment by benchti** [comment]
@oncletom oui j'utilise https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ sur ma première capture d'écran il est en effet activé ( logo rouge en haut à droite) mais je l'ai ensuite désactivé pour le site et vous aider à debugguer. Là en l'activant il ne bloque plus rien. 

Je précise que maintenant la page s'affiche bien ( contrairement à ce matin) ... 

mais que dans firebug je vois qu'il n'arrive pas à charger http://fonts.googleapis.com/css?family=Squada+One:100

**Comment by benchti** [comment]
ah non mais on arrête de se prendre la tête : ma capture d'écran date de 11h49 et le commit de @DirtyF aussi ... on c'est sûrement croisé ... cache tout ça

**Comment by DirtyF** [comment]
@benchti la 404 sur l'appel de la webfont est corrigé, merci.
